HAI 1.2

I HAS A TOTL ITZ 0
I HAS A NUM ITZ 0

IM IN YR LOOP UPPIN YR NUM TIL BOTH SAEM NUM AN 101
    BOTH SAEM MOD OF NUM AN 2 AN 0, O RLY?
        YA RLY
            TOTL R SUM OF TOTL AN NUM
        NO WAI
            BTW Not an even number, do nothing
    OIC
IM OUTTA YR LOOP

VISIBLE "SUM OF EVEN INTEGERS FROM 0 TO 100 IS:"
VISIBLE TOTL

KTHXBYE
